//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.11 at 01:13:59 PM EDT 
//


package org.archiviststoolkit.structure.EAD;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eadheader" type="{urn:isbn:1-931666-22-9}eadheader"/>
 *         &lt;element name="frontmatter" type="{urn:isbn:1-931666-22-9}frontmatter" minOccurs="0"/>
 *         &lt;element name="archdesc" type="{urn:isbn:1-931666-22-9}archdesc"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:isbn:1-931666-22-9}a.common"/>
 *       &lt;attribute name="relatedencoding" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eadheader",
    "frontmatter",
    "archdesc"
})
@XmlRootElement(name = "ead", namespace = "urn:isbn:1-931666-22-9")
public class Ead {

    @XmlElement(namespace = "urn:isbn:1-931666-22-9", required = true)
    protected Eadheader eadheader;
    @XmlElement(namespace = "urn:isbn:1-931666-22-9")
    protected Frontmatter frontmatter;
    @XmlElement(namespace = "urn:isbn:1-931666-22-9", required = true)
    protected Archdesc archdesc;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String relatedencoding;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String altrender;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String audience;

    /**
     * Gets the value of the eadheader property.
     * 
     * @return
     *     possible object is
     *     {@link Eadheader }
     *     
     */
    public Eadheader getEadheader() {
        return eadheader;
    }

    /**
     * Sets the value of the eadheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eadheader }
     *     
     */
    public void setEadheader(Eadheader value) {
        this.eadheader = value;
    }

    /**
     * Gets the value of the frontmatter property.
     * 
     * @return
     *     possible object is
     *     {@link Frontmatter }
     *     
     */
    public Frontmatter getFrontmatter() {
        return frontmatter;
    }

    /**
     * Sets the value of the frontmatter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frontmatter }
     *     
     */
    public void setFrontmatter(Frontmatter value) {
        this.frontmatter = value;
    }

    /**
     * Gets the value of the archdesc property.
     * 
     * @return
     *     possible object is
     *     {@link Archdesc }
     *     
     */
    public Archdesc getArchdesc() {
        return archdesc;
    }

    /**
     * Sets the value of the archdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Archdesc }
     *     
     */
    public void setArchdesc(Archdesc value) {
        this.archdesc = value;
    }

    /**
     * Gets the value of the relatedencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedencoding() {
        return relatedencoding;
    }

    /**
     * Sets the value of the relatedencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedencoding(String value) {
        this.relatedencoding = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the altrender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltrender() {
        return altrender;
    }

    /**
     * Sets the value of the altrender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltrender(String value) {
        this.altrender = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudience(String value) {
        this.audience = value;
    }

}
