//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.11 at 01:13:59 PM EDT 
//


package org.archiviststoolkit.structure.EAD;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for eadheader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eadheader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eadid" type="{urn:isbn:1-931666-22-9}eadid"/>
 *         &lt;element name="filedesc" type="{urn:isbn:1-931666-22-9}filedesc"/>
 *         &lt;element name="profiledesc" type="{urn:isbn:1-931666-22-9}profiledesc" minOccurs="0"/>
 *         &lt;element name="revisiondesc" type="{urn:isbn:1-931666-22-9}revisiondesc" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:isbn:1-931666-22-9}a.common"/>
 *       &lt;attribute name="langencoding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="iso639-2b" />
 *       &lt;attribute name="scriptencoding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="iso15924" />
 *       &lt;attribute name="dateencoding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="iso8601" />
 *       &lt;attribute name="countryencoding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="iso3166-1" />
 *       &lt;attribute name="repositoryencoding" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="iso15511" />
 *       &lt;attribute name="relatedencoding" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="findaidstatus" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="encodinganalog" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eadheader", namespace = "urn:isbn:1-931666-22-9", propOrder = {
    "eadid",
    "filedesc",
    "profiledesc",
    "revisiondesc"
})
public class Eadheader {

    @XmlElement(namespace = "urn:isbn:1-931666-22-9", required = true)
    protected Eadid eadid;
    @XmlElement(namespace = "urn:isbn:1-931666-22-9", required = true)
    protected Filedesc filedesc;
    @XmlElement(namespace = "urn:isbn:1-931666-22-9")
    protected Profiledesc profiledesc;
    @XmlElement(namespace = "urn:isbn:1-931666-22-9")
    protected Revisiondesc revisiondesc;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String langencoding;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String scriptencoding;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dateencoding;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String countryencoding;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String repositoryencoding;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String relatedencoding;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String findaidstatus;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String encodinganalog;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String altrender;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String audience;

    /**
     * Gets the value of the eadid property.
     * 
     * @return
     *     possible object is
     *     {@link Eadid }
     *     
     */
    public Eadid getEadid() {
        return eadid;
    }

    /**
     * Sets the value of the eadid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eadid }
     *     
     */
    public void setEadid(Eadid value) {
        this.eadid = value;
    }

    /**
     * Gets the value of the filedesc property.
     * 
     * @return
     *     possible object is
     *     {@link Filedesc }
     *     
     */
    public Filedesc getFiledesc() {
        return filedesc;
    }

    /**
     * Sets the value of the filedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filedesc }
     *     
     */
    public void setFiledesc(Filedesc value) {
        this.filedesc = value;
    }

    /**
     * Gets the value of the profiledesc property.
     * 
     * @return
     *     possible object is
     *     {@link Profiledesc }
     *     
     */
    public Profiledesc getProfiledesc() {
        return profiledesc;
    }

    /**
     * Sets the value of the profiledesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profiledesc }
     *     
     */
    public void setProfiledesc(Profiledesc value) {
        this.profiledesc = value;
    }

    /**
     * Gets the value of the revisiondesc property.
     * 
     * @return
     *     possible object is
     *     {@link Revisiondesc }
     *     
     */
    public Revisiondesc getRevisiondesc() {
        return revisiondesc;
    }

    /**
     * Sets the value of the revisiondesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Revisiondesc }
     *     
     */
    public void setRevisiondesc(Revisiondesc value) {
        this.revisiondesc = value;
    }

    /**
     * Gets the value of the langencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangencoding() {
        if (langencoding == null) {
            return "iso639-2b";
        } else {
            return langencoding;
        }
    }

    /**
     * Sets the value of the langencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangencoding(String value) {
        this.langencoding = value;
    }

    /**
     * Gets the value of the scriptencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriptencoding() {
        if (scriptencoding == null) {
            return "iso15924";
        } else {
            return scriptencoding;
        }
    }

    /**
     * Sets the value of the scriptencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriptencoding(String value) {
        this.scriptencoding = value;
    }

    /**
     * Gets the value of the dateencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateencoding() {
        if (dateencoding == null) {
            return "iso8601";
        } else {
            return dateencoding;
        }
    }

    /**
     * Sets the value of the dateencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateencoding(String value) {
        this.dateencoding = value;
    }

    /**
     * Gets the value of the countryencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryencoding() {
        if (countryencoding == null) {
            return "iso3166-1";
        } else {
            return countryencoding;
        }
    }

    /**
     * Sets the value of the countryencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryencoding(String value) {
        this.countryencoding = value;
    }

    /**
     * Gets the value of the repositoryencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryencoding() {
        if (repositoryencoding == null) {
            return "iso15511";
        } else {
            return repositoryencoding;
        }
    }

    /**
     * Sets the value of the repositoryencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryencoding(String value) {
        this.repositoryencoding = value;
    }

    /**
     * Gets the value of the relatedencoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedencoding() {
        return relatedencoding;
    }

    /**
     * Sets the value of the relatedencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedencoding(String value) {
        this.relatedencoding = value;
    }

    /**
     * Gets the value of the findaidstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFindaidstatus() {
        return findaidstatus;
    }

    /**
     * Sets the value of the findaidstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFindaidstatus(String value) {
        this.findaidstatus = value;
    }

    /**
     * Gets the value of the encodinganalog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodinganalog() {
        return encodinganalog;
    }

    /**
     * Sets the value of the encodinganalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodinganalog(String value) {
        this.encodinganalog = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the altrender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltrender() {
        return altrender;
    }

    /**
     * Sets the value of the altrender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltrender(String value) {
        this.altrender = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudience(String value) {
        this.audience = value;
    }

}
