//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.27 at 12:28:55 PM EDT 
//


package org.archiviststoolkit.structure.accessionImport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nameComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nameComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Person"/>
 *               &lt;enumeration value="Family"/>
 *               &lt;enumeration value="Corporate Body"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="qualifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nameRule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descriptionType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Administrative History"/>
 *               &lt;enumeration value="Biography"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="descriptionNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="citation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salutation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactRegion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactMailCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="familyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="familyNamePrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="corporatePrimaryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="corporateSubordinate1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="corporateSubordinate2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="personalPrimaryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="personalRestOfName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="personalPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="personalSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="personalDates" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="personalFullerForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="personalTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="personalDirectOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nameComplexType", propOrder = {
    "nameType",
    "sortName",
    "number",
    "qualifier",
    "nameSource",
    "nameRule",
    "descriptionType",
    "descriptionNote",
    "citation",
    "salutation",
    "contactAddress1",
    "contactAddress2",
    "contactCity",
    "contactRegion",
    "contactCountry",
    "contactMailCode",
    "contactPhone",
    "contactFax",
    "contactEmail",
    "contactName",
    "familyName",
    "familyNamePrefix",
    "corporatePrimaryName",
    "corporateSubordinate1",
    "corporateSubordinate2",
    "personalPrimaryName",
    "personalRestOfName",
    "personalPrefix",
    "personalSuffix",
    "personalDates",
    "personalFullerForm",
    "personalTitle",
    "personalDirectOrder"
})
public class NameComplexType {

    @XmlElement(required = true)
    protected String nameType;
    protected String sortName;
    protected String number;
    protected String qualifier;
    protected String nameSource;
    protected String nameRule;
    protected String descriptionType;
    protected String descriptionNote;
    protected String citation;
    protected String salutation;
    protected String contactAddress1;
    protected String contactAddress2;
    protected String contactCity;
    protected String contactRegion;
    protected String contactCountry;
    protected String contactMailCode;
    protected String contactPhone;
    protected String contactFax;
    protected String contactEmail;
    protected String contactName;
    protected String familyName;
    protected String familyNamePrefix;
    protected String corporatePrimaryName;
    protected String corporateSubordinate1;
    protected String corporateSubordinate2;
    protected String personalPrimaryName;
    protected String personalRestOfName;
    protected String personalPrefix;
    protected String personalSuffix;
    protected String personalDates;
    protected String personalFullerForm;
    protected String personalTitle;
    protected Boolean personalDirectOrder;

    /**
     * Gets the value of the nameType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameType() {
        return nameType;
    }

    /**
     * Sets the value of the nameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameType(String value) {
        this.nameType = value;
    }

    /**
     * Gets the value of the sortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * Sets the value of the sortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortName(String value) {
        this.sortName = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the qualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifier() {
        return qualifier;
    }

    /**
     * Sets the value of the qualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifier(String value) {
        this.qualifier = value;
    }

    /**
     * Gets the value of the nameSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSource() {
        return nameSource;
    }

    /**
     * Sets the value of the nameSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSource(String value) {
        this.nameSource = value;
    }

    /**
     * Gets the value of the nameRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRule() {
        return nameRule;
    }

    /**
     * Sets the value of the nameRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRule(String value) {
        this.nameRule = value;
    }

    /**
     * Gets the value of the descriptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionType() {
        return descriptionType;
    }

    /**
     * Sets the value of the descriptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionType(String value) {
        this.descriptionType = value;
    }

    /**
     * Gets the value of the descriptionNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionNote() {
        return descriptionNote;
    }

    /**
     * Sets the value of the descriptionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionNote(String value) {
        this.descriptionNote = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitation(String value) {
        this.citation = value;
    }

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the contactAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress1() {
        return contactAddress1;
    }

    /**
     * Sets the value of the contactAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress1(String value) {
        this.contactAddress1 = value;
    }

    /**
     * Gets the value of the contactAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress2() {
        return contactAddress2;
    }

    /**
     * Sets the value of the contactAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress2(String value) {
        this.contactAddress2 = value;
    }

    /**
     * Gets the value of the contactCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCity() {
        return contactCity;
    }

    /**
     * Sets the value of the contactCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCity(String value) {
        this.contactCity = value;
    }

    /**
     * Gets the value of the contactRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactRegion() {
        return contactRegion;
    }

    /**
     * Sets the value of the contactRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactRegion(String value) {
        this.contactRegion = value;
    }

    /**
     * Gets the value of the contactCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCountry() {
        return contactCountry;
    }

    /**
     * Sets the value of the contactCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCountry(String value) {
        this.contactCountry = value;
    }

    /**
     * Gets the value of the contactMailCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactMailCode() {
        return contactMailCode;
    }

    /**
     * Sets the value of the contactMailCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactMailCode(String value) {
        this.contactMailCode = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the contactFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * Sets the value of the contactFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactFax(String value) {
        this.contactFax = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the familyNamePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyNamePrefix() {
        return familyNamePrefix;
    }

    /**
     * Sets the value of the familyNamePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyNamePrefix(String value) {
        this.familyNamePrefix = value;
    }

    /**
     * Gets the value of the corporatePrimaryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporatePrimaryName() {
        return corporatePrimaryName;
    }

    /**
     * Sets the value of the corporatePrimaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporatePrimaryName(String value) {
        this.corporatePrimaryName = value;
    }

    /**
     * Gets the value of the corporateSubordinate1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateSubordinate1() {
        return corporateSubordinate1;
    }

    /**
     * Sets the value of the corporateSubordinate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateSubordinate1(String value) {
        this.corporateSubordinate1 = value;
    }

    /**
     * Gets the value of the corporateSubordinate2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateSubordinate2() {
        return corporateSubordinate2;
    }

    /**
     * Sets the value of the corporateSubordinate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateSubordinate2(String value) {
        this.corporateSubordinate2 = value;
    }

    /**
     * Gets the value of the personalPrimaryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalPrimaryName() {
        return personalPrimaryName;
    }

    /**
     * Sets the value of the personalPrimaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalPrimaryName(String value) {
        this.personalPrimaryName = value;
    }

    /**
     * Gets the value of the personalRestOfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalRestOfName() {
        return personalRestOfName;
    }

    /**
     * Sets the value of the personalRestOfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalRestOfName(String value) {
        this.personalRestOfName = value;
    }

    /**
     * Gets the value of the personalPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalPrefix() {
        return personalPrefix;
    }

    /**
     * Sets the value of the personalPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalPrefix(String value) {
        this.personalPrefix = value;
    }

    /**
     * Gets the value of the personalSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalSuffix() {
        return personalSuffix;
    }

    /**
     * Sets the value of the personalSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalSuffix(String value) {
        this.personalSuffix = value;
    }

    /**
     * Gets the value of the personalDates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalDates() {
        return personalDates;
    }

    /**
     * Sets the value of the personalDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalDates(String value) {
        this.personalDates = value;
    }

    /**
     * Gets the value of the personalFullerForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalFullerForm() {
        return personalFullerForm;
    }

    /**
     * Sets the value of the personalFullerForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalFullerForm(String value) {
        this.personalFullerForm = value;
    }

    /**
     * Gets the value of the personalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalTitle() {
        return personalTitle;
    }

    /**
     * Sets the value of the personalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalTitle(String value) {
        this.personalTitle = value;
    }

    /**
     * Gets the value of the personalDirectOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPersonalDirectOrder() {
        return personalDirectOrder;
    }

    /**
     * Sets the value of the personalDirectOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPersonalDirectOrder(Boolean value) {
        this.personalDirectOrder = value;
    }

}
