//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.27 at 12:28:55 PM EDT 
//


package org.archiviststoolkit.structure.accessionImport;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for recordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accessionNumber" type="{}identifierType"/>
 *         &lt;element name="accessionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="accessionDispositionNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accessRestrictions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accessRestrictionsNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="useRestrictions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="useRestrictionsNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="generalAccessionNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acknowledgementDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="acknowledgementSent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="agreementReceivedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="agreementSentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="agreementSent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="agreementReceived" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accessionProcessed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accessionProcessedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="acquisitionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateExpression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bulkDateBegin" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="bulkDateEnd" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dateBegin" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dateEnd" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cataloged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="catalogedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="catalogedNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="conditionNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="extentNumber" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="extentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="containerSummary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inventory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processingPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processingPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processingStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processingStartedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="resourceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retentionRule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="restrictionsApply" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rightsTransferred" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rightsTransferredDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="rightsTransferredNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedDate1" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="userDefinedDate2" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="userDefinedBoolean1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="userDefinedBoolean2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="userDefinedInteger1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="userDefinedInteger2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="userDefinedReal1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="userDefinedReal2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="userDefinedString1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedString2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedString3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedText4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceIdentifier" type="{}identifierType" minOccurs="0"/>
 *         &lt;element name="subjectLink" type="{}subjectLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nameLink" type="{}nameLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordType", propOrder = {
    "accessionNumber",
    "accessionDate",
    "accessionDispositionNote",
    "accessRestrictions",
    "accessRestrictionsNote",
    "useRestrictions",
    "useRestrictionsNote",
    "generalAccessionNote",
    "acknowledgementDate",
    "acknowledgementSent",
    "agreementReceivedDate",
    "agreementSentDate",
    "agreementSent",
    "agreementReceived",
    "accessionProcessed",
    "accessionProcessedDate",
    "acquisitionType",
    "dateExpression",
    "bulkDateBegin",
    "bulkDateEnd",
    "dateBegin",
    "dateEnd",
    "description",
    "cataloged",
    "catalogedDate",
    "catalogedNote",
    "conditionNote",
    "extentNumber",
    "extentType",
    "containerSummary",
    "inventory",
    "processingPlan",
    "processingPriority",
    "processors",
    "processingStatus",
    "processingStartedDate",
    "resourceType",
    "retentionRule",
    "title",
    "restrictionsApply",
    "rightsTransferred",
    "rightsTransferredDate",
    "rightsTransferredNote",
    "userDefinedDate1",
    "userDefinedDate2",
    "userDefinedBoolean1",
    "userDefinedBoolean2",
    "userDefinedInteger1",
    "userDefinedInteger2",
    "userDefinedReal1",
    "userDefinedReal2",
    "userDefinedString1",
    "userDefinedString2",
    "userDefinedString3",
    "userDefinedText1",
    "userDefinedText2",
    "userDefinedText3",
    "userDefinedText4",
    "resourceIdentifier",
    "subjectLink",
    "nameLink"
})
public class RecordType {

    @XmlElement(required = true)
    protected IdentifierType accessionNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accessionDate;
    protected String accessionDispositionNote;
    protected Boolean accessRestrictions;
    protected String accessRestrictionsNote;
    protected Boolean useRestrictions;
    protected String useRestrictionsNote;
    protected String generalAccessionNote;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar acknowledgementDate;
    protected Boolean acknowledgementSent;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar agreementReceivedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar agreementSentDate;
    protected Boolean agreementSent;
    protected Boolean agreementReceived;
    protected Boolean accessionProcessed;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accessionProcessedDate;
    protected String acquisitionType;
    protected String dateExpression;
    protected BigInteger bulkDateBegin;
    protected BigInteger bulkDateEnd;
    protected BigInteger dateBegin;
    protected BigInteger dateEnd;
    protected String description;
    protected Boolean cataloged;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar catalogedDate;
    protected String catalogedNote;
    protected String conditionNote;
    protected BigDecimal extentNumber;
    protected String extentType;
    protected String containerSummary;
    protected String inventory;
    protected String processingPlan;
    protected String processingPriority;
    protected String processors;
    protected String processingStatus;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar processingStartedDate;
    protected String resourceType;
    protected String retentionRule;
    protected String title;
    protected Boolean restrictionsApply;
    protected Boolean rightsTransferred;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rightsTransferredDate;
    protected String rightsTransferredNote;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar userDefinedDate1;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar userDefinedDate2;
    protected Boolean userDefinedBoolean1;
    protected Boolean userDefinedBoolean2;
    protected BigInteger userDefinedInteger1;
    protected BigInteger userDefinedInteger2;
    protected BigDecimal userDefinedReal1;
    protected BigDecimal userDefinedReal2;
    protected String userDefinedString1;
    protected String userDefinedString2;
    protected String userDefinedString3;
    protected String userDefinedText1;
    protected String userDefinedText2;
    protected String userDefinedText3;
    protected String userDefinedText4;
    protected IdentifierType resourceIdentifier;
    protected List<SubjectLinkType> subjectLink;
    protected List<NameLinkType> nameLink;

    /**
     * Gets the value of the accessionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getAccessionNumber() {
        return accessionNumber;
    }

    /**
     * Sets the value of the accessionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setAccessionNumber(IdentifierType value) {
        this.accessionNumber = value;
    }

    /**
     * Gets the value of the accessionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccessionDate() {
        return accessionDate;
    }

    /**
     * Sets the value of the accessionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccessionDate(XMLGregorianCalendar value) {
        this.accessionDate = value;
    }

    /**
     * Gets the value of the accessionDispositionNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessionDispositionNote() {
        return accessionDispositionNote;
    }

    /**
     * Sets the value of the accessionDispositionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessionDispositionNote(String value) {
        this.accessionDispositionNote = value;
    }

    /**
     * Gets the value of the accessRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccessRestrictions() {
        return accessRestrictions;
    }

    /**
     * Sets the value of the accessRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccessRestrictions(Boolean value) {
        this.accessRestrictions = value;
    }

    /**
     * Gets the value of the accessRestrictionsNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessRestrictionsNote() {
        return accessRestrictionsNote;
    }

    /**
     * Sets the value of the accessRestrictionsNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessRestrictionsNote(String value) {
        this.accessRestrictionsNote = value;
    }

    /**
     * Gets the value of the useRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseRestrictions() {
        return useRestrictions;
    }

    /**
     * Sets the value of the useRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseRestrictions(Boolean value) {
        this.useRestrictions = value;
    }

    /**
     * Gets the value of the useRestrictionsNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseRestrictionsNote() {
        return useRestrictionsNote;
    }

    /**
     * Sets the value of the useRestrictionsNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseRestrictionsNote(String value) {
        this.useRestrictionsNote = value;
    }

    /**
     * Gets the value of the generalAccessionNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralAccessionNote() {
        return generalAccessionNote;
    }

    /**
     * Sets the value of the generalAccessionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralAccessionNote(String value) {
        this.generalAccessionNote = value;
    }

    /**
     * Gets the value of the acknowledgementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcknowledgementDate() {
        return acknowledgementDate;
    }

    /**
     * Sets the value of the acknowledgementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcknowledgementDate(XMLGregorianCalendar value) {
        this.acknowledgementDate = value;
    }

    /**
     * Gets the value of the acknowledgementSent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcknowledgementSent() {
        return acknowledgementSent;
    }

    /**
     * Sets the value of the acknowledgementSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcknowledgementSent(Boolean value) {
        this.acknowledgementSent = value;
    }

    /**
     * Gets the value of the agreementReceivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAgreementReceivedDate() {
        return agreementReceivedDate;
    }

    /**
     * Sets the value of the agreementReceivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAgreementReceivedDate(XMLGregorianCalendar value) {
        this.agreementReceivedDate = value;
    }

    /**
     * Gets the value of the agreementSentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAgreementSentDate() {
        return agreementSentDate;
    }

    /**
     * Sets the value of the agreementSentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAgreementSentDate(XMLGregorianCalendar value) {
        this.agreementSentDate = value;
    }

    /**
     * Gets the value of the agreementSent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAgreementSent() {
        return agreementSent;
    }

    /**
     * Sets the value of the agreementSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAgreementSent(Boolean value) {
        this.agreementSent = value;
    }

    /**
     * Gets the value of the agreementReceived property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAgreementReceived() {
        return agreementReceived;
    }

    /**
     * Sets the value of the agreementReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAgreementReceived(Boolean value) {
        this.agreementReceived = value;
    }

    /**
     * Gets the value of the accessionProcessed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccessionProcessed() {
        return accessionProcessed;
    }

    /**
     * Sets the value of the accessionProcessed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccessionProcessed(Boolean value) {
        this.accessionProcessed = value;
    }

    /**
     * Gets the value of the accessionProcessedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccessionProcessedDate() {
        return accessionProcessedDate;
    }

    /**
     * Sets the value of the accessionProcessedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccessionProcessedDate(XMLGregorianCalendar value) {
        this.accessionProcessedDate = value;
    }

    /**
     * Gets the value of the acquisitionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionType() {
        return acquisitionType;
    }

    /**
     * Sets the value of the acquisitionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionType(String value) {
        this.acquisitionType = value;
    }

    /**
     * Gets the value of the dateExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateExpression() {
        return dateExpression;
    }

    /**
     * Sets the value of the dateExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateExpression(String value) {
        this.dateExpression = value;
    }

    /**
     * Gets the value of the bulkDateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBulkDateBegin() {
        return bulkDateBegin;
    }

    /**
     * Sets the value of the bulkDateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBulkDateBegin(BigInteger value) {
        this.bulkDateBegin = value;
    }

    /**
     * Gets the value of the bulkDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBulkDateEnd() {
        return bulkDateEnd;
    }

    /**
     * Sets the value of the bulkDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBulkDateEnd(BigInteger value) {
        this.bulkDateEnd = value;
    }

    /**
     * Gets the value of the dateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDateBegin() {
        return dateBegin;
    }

    /**
     * Sets the value of the dateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateBegin(BigInteger value) {
        this.dateBegin = value;
    }

    /**
     * Gets the value of the dateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDateEnd() {
        return dateEnd;
    }

    /**
     * Sets the value of the dateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateEnd(BigInteger value) {
        this.dateEnd = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the cataloged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCataloged() {
        return cataloged;
    }

    /**
     * Sets the value of the cataloged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCataloged(Boolean value) {
        this.cataloged = value;
    }

    /**
     * Gets the value of the catalogedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCatalogedDate() {
        return catalogedDate;
    }

    /**
     * Sets the value of the catalogedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCatalogedDate(XMLGregorianCalendar value) {
        this.catalogedDate = value;
    }

    /**
     * Gets the value of the catalogedNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogedNote() {
        return catalogedNote;
    }

    /**
     * Sets the value of the catalogedNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogedNote(String value) {
        this.catalogedNote = value;
    }

    /**
     * Gets the value of the conditionNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionNote() {
        return conditionNote;
    }

    /**
     * Sets the value of the conditionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionNote(String value) {
        this.conditionNote = value;
    }

    /**
     * Gets the value of the extentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtentNumber() {
        return extentNumber;
    }

    /**
     * Sets the value of the extentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtentNumber(BigDecimal value) {
        this.extentNumber = value;
    }

    /**
     * Gets the value of the extentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtentType() {
        return extentType;
    }

    /**
     * Sets the value of the extentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtentType(String value) {
        this.extentType = value;
    }

    /**
     * Gets the value of the containerSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerSummary() {
        return containerSummary;
    }

    /**
     * Sets the value of the containerSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerSummary(String value) {
        this.containerSummary = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventory(String value) {
        this.inventory = value;
    }

    /**
     * Gets the value of the processingPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingPlan() {
        return processingPlan;
    }

    /**
     * Sets the value of the processingPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingPlan(String value) {
        this.processingPlan = value;
    }

    /**
     * Gets the value of the processingPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingPriority() {
        return processingPriority;
    }

    /**
     * Sets the value of the processingPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingPriority(String value) {
        this.processingPriority = value;
    }

    /**
     * Gets the value of the processors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessors() {
        return processors;
    }

    /**
     * Sets the value of the processors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessors(String value) {
        this.processors = value;
    }

    /**
     * Gets the value of the processingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingStatus() {
        return processingStatus;
    }

    /**
     * Sets the value of the processingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingStatus(String value) {
        this.processingStatus = value;
    }

    /**
     * Gets the value of the processingStartedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessingStartedDate() {
        return processingStartedDate;
    }

    /**
     * Sets the value of the processingStartedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessingStartedDate(XMLGregorianCalendar value) {
        this.processingStartedDate = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceType(String value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the retentionRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetentionRule() {
        return retentionRule;
    }

    /**
     * Sets the value of the retentionRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetentionRule(String value) {
        this.retentionRule = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the restrictionsApply property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRestrictionsApply() {
        return restrictionsApply;
    }

    /**
     * Sets the value of the restrictionsApply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRestrictionsApply(Boolean value) {
        this.restrictionsApply = value;
    }

    /**
     * Gets the value of the rightsTransferred property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRightsTransferred() {
        return rightsTransferred;
    }

    /**
     * Sets the value of the rightsTransferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRightsTransferred(Boolean value) {
        this.rightsTransferred = value;
    }

    /**
     * Gets the value of the rightsTransferredDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRightsTransferredDate() {
        return rightsTransferredDate;
    }

    /**
     * Sets the value of the rightsTransferredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRightsTransferredDate(XMLGregorianCalendar value) {
        this.rightsTransferredDate = value;
    }

    /**
     * Gets the value of the rightsTransferredNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightsTransferredNote() {
        return rightsTransferredNote;
    }

    /**
     * Sets the value of the rightsTransferredNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightsTransferredNote(String value) {
        this.rightsTransferredNote = value;
    }

    /**
     * Gets the value of the userDefinedDate1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUserDefinedDate1() {
        return userDefinedDate1;
    }

    /**
     * Sets the value of the userDefinedDate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUserDefinedDate1(XMLGregorianCalendar value) {
        this.userDefinedDate1 = value;
    }

    /**
     * Gets the value of the userDefinedDate2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUserDefinedDate2() {
        return userDefinedDate2;
    }

    /**
     * Sets the value of the userDefinedDate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUserDefinedDate2(XMLGregorianCalendar value) {
        this.userDefinedDate2 = value;
    }

    /**
     * Gets the value of the userDefinedBoolean1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDefinedBoolean1() {
        return userDefinedBoolean1;
    }

    /**
     * Sets the value of the userDefinedBoolean1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDefinedBoolean1(Boolean value) {
        this.userDefinedBoolean1 = value;
    }

    /**
     * Gets the value of the userDefinedBoolean2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUserDefinedBoolean2() {
        return userDefinedBoolean2;
    }

    /**
     * Sets the value of the userDefinedBoolean2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserDefinedBoolean2(Boolean value) {
        this.userDefinedBoolean2 = value;
    }

    /**
     * Gets the value of the userDefinedInteger1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserDefinedInteger1() {
        return userDefinedInteger1;
    }

    /**
     * Sets the value of the userDefinedInteger1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserDefinedInteger1(BigInteger value) {
        this.userDefinedInteger1 = value;
    }

    /**
     * Gets the value of the userDefinedInteger2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserDefinedInteger2() {
        return userDefinedInteger2;
    }

    /**
     * Sets the value of the userDefinedInteger2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserDefinedInteger2(BigInteger value) {
        this.userDefinedInteger2 = value;
    }

    /**
     * Gets the value of the userDefinedReal1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserDefinedReal1() {
        return userDefinedReal1;
    }

    /**
     * Sets the value of the userDefinedReal1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserDefinedReal1(BigDecimal value) {
        this.userDefinedReal1 = value;
    }

    /**
     * Gets the value of the userDefinedReal2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserDefinedReal2() {
        return userDefinedReal2;
    }

    /**
     * Sets the value of the userDefinedReal2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserDefinedReal2(BigDecimal value) {
        this.userDefinedReal2 = value;
    }

    /**
     * Gets the value of the userDefinedString1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString1() {
        return userDefinedString1;
    }

    /**
     * Sets the value of the userDefinedString1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString1(String value) {
        this.userDefinedString1 = value;
    }

    /**
     * Gets the value of the userDefinedString2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString2() {
        return userDefinedString2;
    }

    /**
     * Sets the value of the userDefinedString2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString2(String value) {
        this.userDefinedString2 = value;
    }

    /**
     * Gets the value of the userDefinedString3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedString3() {
        return userDefinedString3;
    }

    /**
     * Sets the value of the userDefinedString3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedString3(String value) {
        this.userDefinedString3 = value;
    }

    /**
     * Gets the value of the userDefinedText1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText1() {
        return userDefinedText1;
    }

    /**
     * Sets the value of the userDefinedText1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText1(String value) {
        this.userDefinedText1 = value;
    }

    /**
     * Gets the value of the userDefinedText2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText2() {
        return userDefinedText2;
    }

    /**
     * Sets the value of the userDefinedText2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText2(String value) {
        this.userDefinedText2 = value;
    }

    /**
     * Gets the value of the userDefinedText3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText3() {
        return userDefinedText3;
    }

    /**
     * Sets the value of the userDefinedText3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText3(String value) {
        this.userDefinedText3 = value;
    }

    /**
     * Gets the value of the userDefinedText4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedText4() {
        return userDefinedText4;
    }

    /**
     * Sets the value of the userDefinedText4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedText4(String value) {
        this.userDefinedText4 = value;
    }

    /**
     * Gets the value of the resourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getResourceIdentifier() {
        return resourceIdentifier;
    }

    /**
     * Sets the value of the resourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setResourceIdentifier(IdentifierType value) {
        this.resourceIdentifier = value;
    }

    /**
     * Gets the value of the subjectLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subjectLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubjectLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjectLinkType }
     * 
     * 
     */
    public List<SubjectLinkType> getSubjectLink() {
        if (subjectLink == null) {
            subjectLink = new ArrayList<SubjectLinkType>();
        }
        return this.subjectLink;
    }

    /**
     * Gets the value of the nameLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameLinkType }
     * 
     * 
     */
    public List<NameLinkType> getNameLink() {
        if (nameLink == null) {
            nameLink = new ArrayList<NameLinkType>();
        }
        return this.nameLink;
    }

}
