//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.22 at 10:33:51 PM EDT 
//


package org.archiviststoolkit.structure.MODS;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
//import org.archiviststoolkit.structure.MODS.LocationType;
import org.archiviststoolkit.structure.MODS.PhysicalLocationType;
import org.archiviststoolkit.structure.MODS.UrlType;


/**
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="physicalLocation" type="{http://www.loc.gov/mods/v3}physicalLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.loc.gov/mods/v3}urlType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType", propOrder = {
    "physicalLocation",
    "url"
})
public class LocationType {

    @XmlElement(namespace = "http://www.loc.gov/mods/v3")
    protected List<PhysicalLocationType> physicalLocation;
    @XmlElement(namespace = "http://www.loc.gov/mods/v3")
    protected List<UrlType> url;

    /**
     * Gets the value of the physicalLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalLocationType }
     * 
     * 
     */
    public List<PhysicalLocationType> getPhysicalLocation() {
        if (physicalLocation == null) {
            physicalLocation = new ArrayList<PhysicalLocationType>();
        }
        return this.physicalLocation;
    }

    /**
     * Gets the value of the url property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the url property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UrlType }
     * 
     * 
     */
    public List<UrlType> getUrl() {
        if (url == null) {
            url = new ArrayList<UrlType>();
        }
        return this.url;
    }

}
