//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.22 at 10:33:51 PM EDT 
//


package org.archiviststoolkit.structure.MODS;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.archiviststoolkit.structure.MODS.AbstractType;
import org.archiviststoolkit.structure.MODS.AccessConditionType;
import org.archiviststoolkit.structure.MODS.ClassificationType;
import org.archiviststoolkit.structure.MODS.ExtensionType;
import org.archiviststoolkit.structure.MODS.GenreType;
import org.archiviststoolkit.structure.MODS.IdentifierType;
import org.archiviststoolkit.structure.MODS.LanguageType;
import org.archiviststoolkit.structure.MODS.LocationType;
//import org.archiviststoolkit.structure.MODS.ModsType;
import org.archiviststoolkit.structure.MODS.NameType;
import org.archiviststoolkit.structure.MODS.NoteType;
import org.archiviststoolkit.structure.MODS.OriginInfoType;
import org.archiviststoolkit.structure.MODS.PartType;
import org.archiviststoolkit.structure.MODS.PhysicalDescriptionType;
import org.archiviststoolkit.structure.MODS.RecordInfoType;
import org.archiviststoolkit.structure.MODS.RelatedItemType;
import org.archiviststoolkit.structure.MODS.SubjectType;
import org.archiviststoolkit.structure.MODS.TableOfContentsType;
import org.archiviststoolkit.structure.MODS.TargetAudienceType;
import org.archiviststoolkit.structure.MODS.TitleInfoType;
import org.archiviststoolkit.structure.MODS.TypeOfResourceType;


/**
 * <p>Java class for modsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.loc.gov/mods/v3}modsGroup" maxOccurs="unbounded"/>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="version" type="{http://www.loc.gov/mods/v3}versionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modsType", propOrder = {
    "modsGroup"
})
public class ModsType {

    @XmlElements({
        @XmlElement(name = "subject", namespace = "http://www.loc.gov/mods/v3", type = SubjectType.class),
        @XmlElement(name = "genre", namespace = "http://www.loc.gov/mods/v3", type = GenreType.class),
        @XmlElement(name = "accessCondition", namespace = "http://www.loc.gov/mods/v3", type = AccessConditionType.class),
        @XmlElement(name = "location", namespace = "http://www.loc.gov/mods/v3", type = LocationType.class),
        @XmlElement(name = "identifier", namespace = "http://www.loc.gov/mods/v3", type = IdentifierType.class),
        @XmlElement(name = "originInfo", namespace = "http://www.loc.gov/mods/v3", type = OriginInfoType.class),
        @XmlElement(name = "relatedItem", namespace = "http://www.loc.gov/mods/v3", type = RelatedItemType.class),
        @XmlElement(name = "tableOfContents", namespace = "http://www.loc.gov/mods/v3", type = TableOfContentsType.class),
        @XmlElement(name = "extension", namespace = "http://www.loc.gov/mods/v3", type = ExtensionType.class),
        @XmlElement(name = "typeOfResource", namespace = "http://www.loc.gov/mods/v3", type = TypeOfResourceType.class),
        @XmlElement(name = "titleInfo", namespace = "http://www.loc.gov/mods/v3", type = TitleInfoType.class),
        @XmlElement(name = "part", namespace = "http://www.loc.gov/mods/v3", type = PartType.class),
        @XmlElement(name = "name", namespace = "http://www.loc.gov/mods/v3", type = NameType.class),
        @XmlElement(name = "language", namespace = "http://www.loc.gov/mods/v3", type = LanguageType.class),
        @XmlElement(name = "physicalDescription", namespace = "http://www.loc.gov/mods/v3", type = PhysicalDescriptionType.class),
        @XmlElement(name = "classification", namespace = "http://www.loc.gov/mods/v3", type = ClassificationType.class),
        @XmlElement(name = "abstract", namespace = "http://www.loc.gov/mods/v3", type = AbstractType.class),
        @XmlElement(name = "targetAudience", namespace = "http://www.loc.gov/mods/v3", type = TargetAudienceType.class),
        @XmlElement(name = "note", namespace = "http://www.loc.gov/mods/v3", type = NoteType.class),
        @XmlElement(name = "recordInfo", namespace = "http://www.loc.gov/mods/v3", type = RecordInfoType.class)
    })
    protected List<Object> modsGroup;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the modsGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modsGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModsGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjectType }
     * {@link GenreType }
     * {@link AccessConditionType }
     * {@link LocationType }
     * {@link IdentifierType }
     * {@link OriginInfoType }
     * {@link RelatedItemType }
     * {@link TableOfContentsType }
     * {@link ExtensionType }
     * {@link TypeOfResourceType }
     * {@link TitleInfoType }
     * {@link PartType }
     * {@link NameType }
     * {@link LanguageType }
     * {@link PhysicalDescriptionType }
     * {@link ClassificationType }
     * {@link AbstractType }
     * {@link TargetAudienceType }
     * {@link NoteType }
     * {@link RecordInfoType }
     * 
     * 
     */
    public List<Object> getModsGroup() {
        if (modsGroup == null) {
            modsGroup = new ArrayList<Object>();
        }
        return this.modsGroup;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
