//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.22 at 10:33:51 PM EDT 
//


package org.archiviststoolkit.structure.MODS;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.archiviststoolkit.structure.MODS.AbstractType;
import org.archiviststoolkit.structure.MODS.AccessConditionType;
import org.archiviststoolkit.structure.MODS.ClassificationType;
import org.archiviststoolkit.structure.MODS.ExtensionType;
import org.archiviststoolkit.structure.MODS.GenreType;
import org.archiviststoolkit.structure.MODS.IdentifierType;
import org.archiviststoolkit.structure.MODS.LanguageType;
import org.archiviststoolkit.structure.MODS.LocationType;
import org.archiviststoolkit.structure.MODS.NameType;
import org.archiviststoolkit.structure.MODS.NoteType;
import org.archiviststoolkit.structure.MODS.OriginInfoType;
import org.archiviststoolkit.structure.MODS.PartType;
import org.archiviststoolkit.structure.MODS.PhysicalDescriptionType;
import org.archiviststoolkit.structure.MODS.RecordInfoType;
//import org.archiviststoolkit.structure.MODS.RelatedItemType;
import org.archiviststoolkit.structure.MODS.SubjectType;
import org.archiviststoolkit.structure.MODS.TableOfContentsType;
import org.archiviststoolkit.structure.MODS.TargetAudienceType;
import org.archiviststoolkit.structure.MODS.TitleInfoType;
import org.archiviststoolkit.structure.MODS.TypeOfResourceType;


/**
 * <p>Java class for relatedItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relatedItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.loc.gov/mods/v3}modsGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}simpleLink"/>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="displayLabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="preceding"/>
 *             &lt;enumeration value="succeeding"/>
 *             &lt;enumeration value="original"/>
 *             &lt;enumeration value="host"/>
 *             &lt;enumeration value="constituent"/>
 *             &lt;enumeration value="series"/>
 *             &lt;enumeration value="otherVersion"/>
 *             &lt;enumeration value="otherFormat"/>
 *             &lt;enumeration value="isReferencedBy"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedItemType", propOrder = {
    "modsGroup"
})
public class RelatedItemType {

    @XmlElements({
        @XmlElement(name = "language", namespace = "http://www.loc.gov/mods/v3", type = LanguageType.class),
        @XmlElement(name = "tableOfContents", namespace = "http://www.loc.gov/mods/v3", type = TableOfContentsType.class),
        @XmlElement(name = "recordInfo", namespace = "http://www.loc.gov/mods/v3", type = RecordInfoType.class),
        @XmlElement(name = "accessCondition", namespace = "http://www.loc.gov/mods/v3", type = AccessConditionType.class),
        @XmlElement(name = "identifier", namespace = "http://www.loc.gov/mods/v3", type = IdentifierType.class),
        @XmlElement(name = "subject", namespace = "http://www.loc.gov/mods/v3", type = SubjectType.class),
        @XmlElement(name = "name", namespace = "http://www.loc.gov/mods/v3", type = NameType.class),
        @XmlElement(name = "targetAudience", namespace = "http://www.loc.gov/mods/v3", type = TargetAudienceType.class),
        @XmlElement(name = "relatedItem", namespace = "http://www.loc.gov/mods/v3", type = RelatedItemType.class),
        @XmlElement(name = "location", namespace = "http://www.loc.gov/mods/v3", type = LocationType.class),
        @XmlElement(name = "typeOfResource", namespace = "http://www.loc.gov/mods/v3", type = TypeOfResourceType.class),
        @XmlElement(name = "physicalDescription", namespace = "http://www.loc.gov/mods/v3", type = PhysicalDescriptionType.class),
        @XmlElement(name = "extension", namespace = "http://www.loc.gov/mods/v3", type = ExtensionType.class),
        @XmlElement(name = "titleInfo", namespace = "http://www.loc.gov/mods/v3", type = TitleInfoType.class),
        @XmlElement(name = "classification", namespace = "http://www.loc.gov/mods/v3", type = ClassificationType.class),
        @XmlElement(name = "part", namespace = "http://www.loc.gov/mods/v3", type = PartType.class),
        @XmlElement(name = "abstract", namespace = "http://www.loc.gov/mods/v3", type = AbstractType.class),
        @XmlElement(name = "genre", namespace = "http://www.loc.gov/mods/v3", type = GenreType.class),
        @XmlElement(name = "note", namespace = "http://www.loc.gov/mods/v3", type = NoteType.class),
        @XmlElement(name = "originInfo", namespace = "http://www.loc.gov/mods/v3", type = OriginInfoType.class)
    })
    protected List<Object> modsGroup;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String displayLabel;
    @XmlAttribute(name = "type")
    protected String riType;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String actuate;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String arcrole;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String href;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String role;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String show;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String type;

    /**
     * Gets the value of the modsGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modsGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModsGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguageType }
     * {@link TableOfContentsType }
     * {@link RecordInfoType }
     * {@link AccessConditionType }
     * {@link IdentifierType }
     * {@link SubjectType }
     * {@link NameType }
     * {@link TargetAudienceType }
     * {@link RelatedItemType }
     * {@link LocationType }
     * {@link TypeOfResourceType }
     * {@link PhysicalDescriptionType }
     * {@link ExtensionType }
     * {@link TitleInfoType }
     * {@link ClassificationType }
     * {@link PartType }
     * {@link AbstractType }
     * {@link GenreType }
     * {@link NoteType }
     * {@link OriginInfoType }
     * 
     * 
     */
    public List<Object> getModsGroup() {
        if (modsGroup == null) {
            modsGroup = new ArrayList<Object>();
        }
        return this.modsGroup;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the displayLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayLabel() {
        return displayLabel;
    }

    /**
     * Sets the value of the displayLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayLabel(String value) {
        this.displayLabel = value;
    }

    /**
     * Gets the value of the riType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiType() {
        return riType;
    }

    /**
     * Sets the value of the riType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiType(String value) {
        this.riType = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

    /**
     * Gets the value of the arcrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "simple";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
